# Generated by Django 2.2.24 on 2022-09-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=50, unique=True, verbose_name='Telefono')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('genero', models.PositiveSmallIntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')])),
                ('mensaje', models.CharField(blank=True, max_length=150, verbose_name='Mensaje')),
            ],
        ),
    ]
