# Generated by Django 2.2.24 on 2022-09-19 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='genero',
            new_name='type_genero',
        ),
    ]
